[settings]
experimental = true

# NOTE: enable this only in local configs, comes with performance penalty!
# https://mise.jdx.dev/configuration.html#idiomatic-version-files
# idiomatic_version_file_enable_tools = ["terraform", "opentofu", "python"]

[tools]
# required for auto-completion by mise itself
usage = "latest"

# misc
viddy = "latest"
kafkactl = "latest"
oras = "latest"
"ubi:lindell/multi-gitter" = "latest"

# eso
opa = "latest"
regal = "latest"
kcl = "latest"
# "aqua:kcl-lang/kcl" = "latest" # https://github.com/kcl-lang/kcl.nvim/issues/18

# cloud
aws-cli = "latest"

# IaC
terraform = "latest"
opentofu = "latest"
"ubi:busser/tfautomv" = "latest"
terraform-docs = "latest"

# k8s
kubectl = "latest"
"aqua:kubecolor/kubecolor" = "latest"
"aqua:danielfoehrKn/kubeswitch" = "latest"
krew = "latest"
k9s = "latest"
istioctl = "latest"
argocd = "latest"
"aqua:fluxcd/flux2" = "2.5.1"
kubeone = "latest"
crossplane-cli = "latest"
"ubi:vitobotta/hetzner-k3s" = "latest"
# "http:up" = {version = "v0.41.0", url = "https://cli.upbound.io/stable/{{version}}/bin/linux_amd64/up"} # or version="current"

# krew plugins
# - get-all
# - rbac-tool
# - tree
# - who-can
# - resource-capacity
# - blame
