[settings]
experimental = true

# NOTE: enable this only in local configs, comes with performance penalty!
# https://mise.jdx.dev/configuration.html#idiomatic-version-files
# idiomatic_version_file_enable_tools = ["terraform", "opentofu", "python"]

[tools]
# required for auto-completion by mise itself
usage = "latest"
# required for aqua verifications
slsa-verifier = "latest"

# misc
oras = "latest"

# git
"ubi:lindell/multi-gitter" = "latest"

# code
opa = "latest"
regal = "latest"
kcl = "latest"
# "aqua:kcl-lang/kcl" = "latest" # -> AUR for vscode -> add mise bin path?

# kafka
kafkactl = "latest"

# cloud
aws-cli = "latest"

# IaC
terraform = "latest"
opentofu = "latest"
"ubi:busser/tfautomv" = "latest"

# k8s related
kubectl = "latest"
"aqua:kubecolor/kubecolor" = "latest"
krew = "latest"
k9s = "latest"
istioctl = "latest"
argocd = "latest"
"aqua:fluxcd/flux2" = "2.5.1"
kubeone = "latest"
crossplane-cli = "latest"
"ubi:vitobotta/hetzner-k3s" = "latest"
# "http:up" = {version = "v0.41.0", url = "https://cli.upbound.io/stable/{{version}}/bin/linux_amd64/up"} # or version="current"


# krew plugins
# get-all
# rbac-tool
# tree
# who-can
# resource-capacity
